// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "WhisperTextProtocol.pb.h"
// @@protoc_insertion_point(imports)

@implementation WhisperTextProtocolRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [WhisperTextProtocolRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface WhisperMessage ()
@property (strong) NSData* ratchetKey;
@property UInt32 counter;
@property UInt32 previousCounter;
@property (strong) NSData* ciphertext;
@end

@implementation WhisperMessage

- (BOOL) hasRatchetKey {
  return !!hasRatchetKey_;
}
- (void) setHasRatchetKey:(BOOL) value_ {
  hasRatchetKey_ = !!value_;
}
@synthesize ratchetKey;
- (BOOL) hasCounter {
  return !!hasCounter_;
}
- (void) setHasCounter:(BOOL) value_ {
  hasCounter_ = !!value_;
}
@synthesize counter;
- (BOOL) hasPreviousCounter {
  return !!hasPreviousCounter_;
}
- (void) setHasPreviousCounter:(BOOL) value_ {
  hasPreviousCounter_ = !!value_;
}
@synthesize previousCounter;
- (BOOL) hasCiphertext {
  return !!hasCiphertext_;
}
- (void) setHasCiphertext:(BOOL) value_ {
  hasCiphertext_ = !!value_;
}
@synthesize ciphertext;
- (id) init {
  if ((self = [super init])) {
    self.ratchetKey = [NSData data];
    self.counter = 0;
    self.previousCounter = 0;
    self.ciphertext = [NSData data];
  }
  return self;
}
static WhisperMessage* defaultWhisperMessageInstance = nil;
+ (void) initialize {
  if (self == [WhisperMessage class]) {
    defaultWhisperMessageInstance = [[WhisperMessage alloc] init];
  }
}
+ (WhisperMessage*) defaultInstance {
  return defaultWhisperMessageInstance;
}
- (WhisperMessage*) defaultInstance {
  return defaultWhisperMessageInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasRatchetKey) {
    [output writeData:1 value:self.ratchetKey];
  }
  if (self.hasCounter) {
    [output writeUInt32:2 value:self.counter];
  }
  if (self.hasPreviousCounter) {
    [output writeUInt32:3 value:self.previousCounter];
  }
  if (self.hasCiphertext) {
    [output writeData:4 value:self.ciphertext];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasRatchetKey) {
    size_ += computeDataSize(1, self.ratchetKey);
  }
  if (self.hasCounter) {
    size_ += computeUInt32Size(2, self.counter);
  }
  if (self.hasPreviousCounter) {
    size_ += computeUInt32Size(3, self.previousCounter);
  }
  if (self.hasCiphertext) {
    size_ += computeDataSize(4, self.ciphertext);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (WhisperMessage*) parseFromData:(NSData*) data {
  return (WhisperMessage*)[[[WhisperMessage builder] mergeFromData:data] build];
}
+ (WhisperMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (WhisperMessage*)[[[WhisperMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (WhisperMessage*) parseFromInputStream:(NSInputStream*) input {
  return (WhisperMessage*)[[[WhisperMessage builder] mergeFromInputStream:input] build];
}
+ (WhisperMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (WhisperMessage*)[[[WhisperMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (WhisperMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (WhisperMessage*)[[[WhisperMessage builder] mergeFromCodedInputStream:input] build];
}
+ (WhisperMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (WhisperMessage*)[[[WhisperMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (WhisperMessageBuilder*) builder {
  return [[WhisperMessageBuilder alloc] init];
}
+ (WhisperMessageBuilder*) builderWithPrototype:(WhisperMessage*) prototype {
  return [[WhisperMessage builder] mergeFrom:prototype];
}
- (WhisperMessageBuilder*) builder {
  return [WhisperMessage builder];
}
- (WhisperMessageBuilder*) toBuilder {
  return [WhisperMessage builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasRatchetKey) {
    [output appendFormat:@"%@%@: %@\n", indent, @"ratchetKey", self.ratchetKey];
  }
  if (self.hasCounter) {
    [output appendFormat:@"%@%@: %@\n", indent, @"counter", [NSNumber numberWithInteger:self.counter]];
  }
  if (self.hasPreviousCounter) {
    [output appendFormat:@"%@%@: %@\n", indent, @"previousCounter", [NSNumber numberWithInteger:self.previousCounter]];
  }
  if (self.hasCiphertext) {
    [output appendFormat:@"%@%@: %@\n", indent, @"ciphertext", self.ciphertext];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[WhisperMessage class]]) {
    return NO;
  }
  WhisperMessage *otherMessage = other;
  return
      self.hasRatchetKey == otherMessage.hasRatchetKey &&
      (!self.hasRatchetKey || [self.ratchetKey isEqual:otherMessage.ratchetKey]) &&
      self.hasCounter == otherMessage.hasCounter &&
      (!self.hasCounter || self.counter == otherMessage.counter) &&
      self.hasPreviousCounter == otherMessage.hasPreviousCounter &&
      (!self.hasPreviousCounter || self.previousCounter == otherMessage.previousCounter) &&
      self.hasCiphertext == otherMessage.hasCiphertext &&
      (!self.hasCiphertext || [self.ciphertext isEqual:otherMessage.ciphertext]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasRatchetKey) {
    hashCode = hashCode * 31 + [self.ratchetKey hash];
  }
  if (self.hasCounter) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.counter] hash];
  }
  if (self.hasPreviousCounter) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.previousCounter] hash];
  }
  if (self.hasCiphertext) {
    hashCode = hashCode * 31 + [self.ciphertext hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface WhisperMessageBuilder()
@property (strong) WhisperMessage* result;
@end

@implementation WhisperMessageBuilder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[WhisperMessage alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (WhisperMessageBuilder*) clear {
  self.result = [[WhisperMessage alloc] init];
  return self;
}
- (WhisperMessageBuilder*) clone {
  return [WhisperMessage builderWithPrototype:result];
}
- (WhisperMessage*) defaultInstance {
  return [WhisperMessage defaultInstance];
}
- (WhisperMessage*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (WhisperMessage*) buildPartial {
  WhisperMessage* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (WhisperMessageBuilder*) mergeFrom:(WhisperMessage*) other {
  if (other == [WhisperMessage defaultInstance]) {
    return self;
  }
  if (other.hasRatchetKey) {
    [self setRatchetKey:other.ratchetKey];
  }
  if (other.hasCounter) {
    [self setCounter:other.counter];
  }
  if (other.hasPreviousCounter) {
    [self setPreviousCounter:other.previousCounter];
  }
  if (other.hasCiphertext) {
    [self setCiphertext:other.ciphertext];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (WhisperMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (WhisperMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setRatchetKey:[input readData]];
        break;
      }
      case 16: {
        [self setCounter:[input readUInt32]];
        break;
      }
      case 24: {
        [self setPreviousCounter:[input readUInt32]];
        break;
      }
      case 34: {
        [self setCiphertext:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasRatchetKey {
  return result.hasRatchetKey;
}
- (NSData*) ratchetKey {
  return result.ratchetKey;
}
- (WhisperMessageBuilder*) setRatchetKey:(NSData*) value {
  result.hasRatchetKey = YES;
  result.ratchetKey = value;
  return self;
}
- (WhisperMessageBuilder*) clearRatchetKey {
  result.hasRatchetKey = NO;
  result.ratchetKey = [NSData data];
  return self;
}
- (BOOL) hasCounter {
  return result.hasCounter;
}
- (UInt32) counter {
  return result.counter;
}
- (WhisperMessageBuilder*) setCounter:(UInt32) value {
  result.hasCounter = YES;
  result.counter = value;
  return self;
}
- (WhisperMessageBuilder*) clearCounter {
  result.hasCounter = NO;
  result.counter = 0;
  return self;
}
- (BOOL) hasPreviousCounter {
  return result.hasPreviousCounter;
}
- (UInt32) previousCounter {
  return result.previousCounter;
}
- (WhisperMessageBuilder*) setPreviousCounter:(UInt32) value {
  result.hasPreviousCounter = YES;
  result.previousCounter = value;
  return self;
}
- (WhisperMessageBuilder*) clearPreviousCounter {
  result.hasPreviousCounter = NO;
  result.previousCounter = 0;
  return self;
}
- (BOOL) hasCiphertext {
  return result.hasCiphertext;
}
- (NSData*) ciphertext {
  return result.ciphertext;
}
- (WhisperMessageBuilder*) setCiphertext:(NSData*) value {
  result.hasCiphertext = YES;
  result.ciphertext = value;
  return self;
}
- (WhisperMessageBuilder*) clearCiphertext {
  result.hasCiphertext = NO;
  result.ciphertext = [NSData data];
  return self;
}
@end

@interface PreKeyWhisperMessage ()
@property UInt32 registrationId;
@property UInt32 preKeyId;
@property UInt32 signedPreKeyId;
@property (strong) NSData* baseKey;
@property (strong) NSData* identityKey;
@property (strong) NSData* message;
@end

@implementation PreKeyWhisperMessage

- (BOOL) hasRegistrationId {
  return !!hasRegistrationId_;
}
- (void) setHasRegistrationId:(BOOL) value_ {
  hasRegistrationId_ = !!value_;
}
@synthesize registrationId;
- (BOOL) hasPreKeyId {
  return !!hasPreKeyId_;
}
- (void) setHasPreKeyId:(BOOL) value_ {
  hasPreKeyId_ = !!value_;
}
@synthesize preKeyId;
- (BOOL) hasSignedPreKeyId {
  return !!hasSignedPreKeyId_;
}
- (void) setHasSignedPreKeyId:(BOOL) value_ {
  hasSignedPreKeyId_ = !!value_;
}
@synthesize signedPreKeyId;
- (BOOL) hasBaseKey {
  return !!hasBaseKey_;
}
- (void) setHasBaseKey:(BOOL) value_ {
  hasBaseKey_ = !!value_;
}
@synthesize baseKey;
- (BOOL) hasIdentityKey {
  return !!hasIdentityKey_;
}
- (void) setHasIdentityKey:(BOOL) value_ {
  hasIdentityKey_ = !!value_;
}
@synthesize identityKey;
- (BOOL) hasMessage {
  return !!hasMessage_;
}
- (void) setHasMessage:(BOOL) value_ {
  hasMessage_ = !!value_;
}
@synthesize message;
- (id) init {
  if ((self = [super init])) {
    self.registrationId = 0;
    self.preKeyId = 0;
    self.signedPreKeyId = 0;
    self.baseKey = [NSData data];
    self.identityKey = [NSData data];
    self.message = [NSData data];
  }
  return self;
}
static PreKeyWhisperMessage* defaultPreKeyWhisperMessageInstance = nil;
+ (void) initialize {
  if (self == [PreKeyWhisperMessage class]) {
    defaultPreKeyWhisperMessageInstance = [[PreKeyWhisperMessage alloc] init];
  }
}
+ (PreKeyWhisperMessage*) defaultInstance {
  return defaultPreKeyWhisperMessageInstance;
}
- (PreKeyWhisperMessage*) defaultInstance {
  return defaultPreKeyWhisperMessageInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasPreKeyId) {
    [output writeUInt32:1 value:self.preKeyId];
  }
  if (self.hasBaseKey) {
    [output writeData:2 value:self.baseKey];
  }
  if (self.hasIdentityKey) {
    [output writeData:3 value:self.identityKey];
  }
  if (self.hasMessage) {
    [output writeData:4 value:self.message];
  }
  if (self.hasRegistrationId) {
    [output writeUInt32:5 value:self.registrationId];
  }
  if (self.hasSignedPreKeyId) {
    [output writeUInt32:6 value:self.signedPreKeyId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasPreKeyId) {
    size_ += computeUInt32Size(1, self.preKeyId);
  }
  if (self.hasBaseKey) {
    size_ += computeDataSize(2, self.baseKey);
  }
  if (self.hasIdentityKey) {
    size_ += computeDataSize(3, self.identityKey);
  }
  if (self.hasMessage) {
    size_ += computeDataSize(4, self.message);
  }
  if (self.hasRegistrationId) {
    size_ += computeUInt32Size(5, self.registrationId);
  }
  if (self.hasSignedPreKeyId) {
    size_ += computeUInt32Size(6, self.signedPreKeyId);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PreKeyWhisperMessage*) parseFromData:(NSData*) data {
  return (PreKeyWhisperMessage*)[[[PreKeyWhisperMessage builder] mergeFromData:data] build];
}
+ (PreKeyWhisperMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PreKeyWhisperMessage*)[[[PreKeyWhisperMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PreKeyWhisperMessage*) parseFromInputStream:(NSInputStream*) input {
  return (PreKeyWhisperMessage*)[[[PreKeyWhisperMessage builder] mergeFromInputStream:input] build];
}
+ (PreKeyWhisperMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PreKeyWhisperMessage*)[[[PreKeyWhisperMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PreKeyWhisperMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PreKeyWhisperMessage*)[[[PreKeyWhisperMessage builder] mergeFromCodedInputStream:input] build];
}
+ (PreKeyWhisperMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PreKeyWhisperMessage*)[[[PreKeyWhisperMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PreKeyWhisperMessageBuilder*) builder {
  return [[PreKeyWhisperMessageBuilder alloc] init];
}
+ (PreKeyWhisperMessageBuilder*) builderWithPrototype:(PreKeyWhisperMessage*) prototype {
  return [[PreKeyWhisperMessage builder] mergeFrom:prototype];
}
- (PreKeyWhisperMessageBuilder*) builder {
  return [PreKeyWhisperMessage builder];
}
- (PreKeyWhisperMessageBuilder*) toBuilder {
  return [PreKeyWhisperMessage builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasPreKeyId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"preKeyId", [NSNumber numberWithInteger:self.preKeyId]];
  }
  if (self.hasBaseKey) {
    [output appendFormat:@"%@%@: %@\n", indent, @"baseKey", self.baseKey];
  }
  if (self.hasIdentityKey) {
    [output appendFormat:@"%@%@: %@\n", indent, @"identityKey", self.identityKey];
  }
  if (self.hasMessage) {
    [output appendFormat:@"%@%@: %@\n", indent, @"message", self.message];
  }
  if (self.hasRegistrationId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"registrationId", [NSNumber numberWithInteger:self.registrationId]];
  }
  if (self.hasSignedPreKeyId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"signedPreKeyId", [NSNumber numberWithInteger:self.signedPreKeyId]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PreKeyWhisperMessage class]]) {
    return NO;
  }
  PreKeyWhisperMessage *otherMessage = other;
  return
      self.hasPreKeyId == otherMessage.hasPreKeyId &&
      (!self.hasPreKeyId || self.preKeyId == otherMessage.preKeyId) &&
      self.hasBaseKey == otherMessage.hasBaseKey &&
      (!self.hasBaseKey || [self.baseKey isEqual:otherMessage.baseKey]) &&
      self.hasIdentityKey == otherMessage.hasIdentityKey &&
      (!self.hasIdentityKey || [self.identityKey isEqual:otherMessage.identityKey]) &&
      self.hasMessage == otherMessage.hasMessage &&
      (!self.hasMessage || [self.message isEqual:otherMessage.message]) &&
      self.hasRegistrationId == otherMessage.hasRegistrationId &&
      (!self.hasRegistrationId || self.registrationId == otherMessage.registrationId) &&
      self.hasSignedPreKeyId == otherMessage.hasSignedPreKeyId &&
      (!self.hasSignedPreKeyId || self.signedPreKeyId == otherMessage.signedPreKeyId) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasPreKeyId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.preKeyId] hash];
  }
  if (self.hasBaseKey) {
    hashCode = hashCode * 31 + [self.baseKey hash];
  }
  if (self.hasIdentityKey) {
    hashCode = hashCode * 31 + [self.identityKey hash];
  }
  if (self.hasMessage) {
    hashCode = hashCode * 31 + [self.message hash];
  }
  if (self.hasRegistrationId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.registrationId] hash];
  }
  if (self.hasSignedPreKeyId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.signedPreKeyId] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PreKeyWhisperMessageBuilder()
@property (strong) PreKeyWhisperMessage* result;
@end

@implementation PreKeyWhisperMessageBuilder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[PreKeyWhisperMessage alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PreKeyWhisperMessageBuilder*) clear {
  self.result = [[PreKeyWhisperMessage alloc] init];
  return self;
}
- (PreKeyWhisperMessageBuilder*) clone {
  return [PreKeyWhisperMessage builderWithPrototype:result];
}
- (PreKeyWhisperMessage*) defaultInstance {
  return [PreKeyWhisperMessage defaultInstance];
}
- (PreKeyWhisperMessage*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PreKeyWhisperMessage*) buildPartial {
  PreKeyWhisperMessage* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (PreKeyWhisperMessageBuilder*) mergeFrom:(PreKeyWhisperMessage*) other {
  if (other == [PreKeyWhisperMessage defaultInstance]) {
    return self;
  }
  if (other.hasRegistrationId) {
    [self setRegistrationId:other.registrationId];
  }
  if (other.hasPreKeyId) {
    [self setPreKeyId:other.preKeyId];
  }
  if (other.hasSignedPreKeyId) {
    [self setSignedPreKeyId:other.signedPreKeyId];
  }
  if (other.hasBaseKey) {
    [self setBaseKey:other.baseKey];
  }
  if (other.hasIdentityKey) {
    [self setIdentityKey:other.identityKey];
  }
  if (other.hasMessage) {
    [self setMessage:other.message];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PreKeyWhisperMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PreKeyWhisperMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setPreKeyId:[input readUInt32]];
        break;
      }
      case 18: {
        [self setBaseKey:[input readData]];
        break;
      }
      case 26: {
        [self setIdentityKey:[input readData]];
        break;
      }
      case 34: {
        [self setMessage:[input readData]];
        break;
      }
      case 40: {
        [self setRegistrationId:[input readUInt32]];
        break;
      }
      case 48: {
        [self setSignedPreKeyId:[input readUInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasRegistrationId {
  return result.hasRegistrationId;
}
- (UInt32) registrationId {
  return result.registrationId;
}
- (PreKeyWhisperMessageBuilder*) setRegistrationId:(UInt32) value {
  result.hasRegistrationId = YES;
  result.registrationId = value;
  return self;
}
- (PreKeyWhisperMessageBuilder*) clearRegistrationId {
  result.hasRegistrationId = NO;
  result.registrationId = 0;
  return self;
}
- (BOOL) hasPreKeyId {
  return result.hasPreKeyId;
}
- (UInt32) preKeyId {
  return result.preKeyId;
}
- (PreKeyWhisperMessageBuilder*) setPreKeyId:(UInt32) value {
  result.hasPreKeyId = YES;
  result.preKeyId = value;
  return self;
}
- (PreKeyWhisperMessageBuilder*) clearPreKeyId {
  result.hasPreKeyId = NO;
  result.preKeyId = 0;
  return self;
}
- (BOOL) hasSignedPreKeyId {
  return result.hasSignedPreKeyId;
}
- (UInt32) signedPreKeyId {
  return result.signedPreKeyId;
}
- (PreKeyWhisperMessageBuilder*) setSignedPreKeyId:(UInt32) value {
  result.hasSignedPreKeyId = YES;
  result.signedPreKeyId = value;
  return self;
}
- (PreKeyWhisperMessageBuilder*) clearSignedPreKeyId {
  result.hasSignedPreKeyId = NO;
  result.signedPreKeyId = 0;
  return self;
}
- (BOOL) hasBaseKey {
  return result.hasBaseKey;
}
- (NSData*) baseKey {
  return result.baseKey;
}
- (PreKeyWhisperMessageBuilder*) setBaseKey:(NSData*) value {
  result.hasBaseKey = YES;
  result.baseKey = value;
  return self;
}
- (PreKeyWhisperMessageBuilder*) clearBaseKey {
  result.hasBaseKey = NO;
  result.baseKey = [NSData data];
  return self;
}
- (BOOL) hasIdentityKey {
  return result.hasIdentityKey;
}
- (NSData*) identityKey {
  return result.identityKey;
}
- (PreKeyWhisperMessageBuilder*) setIdentityKey:(NSData*) value {
  result.hasIdentityKey = YES;
  result.identityKey = value;
  return self;
}
- (PreKeyWhisperMessageBuilder*) clearIdentityKey {
  result.hasIdentityKey = NO;
  result.identityKey = [NSData data];
  return self;
}
- (BOOL) hasMessage {
  return result.hasMessage;
}
- (NSData*) message {
  return result.message;
}
- (PreKeyWhisperMessageBuilder*) setMessage:(NSData*) value {
  result.hasMessage = YES;
  result.message = value;
  return self;
}
- (PreKeyWhisperMessageBuilder*) clearMessage {
  result.hasMessage = NO;
  result.message = [NSData data];
  return self;
}
@end

@interface KeyExchangeMessage ()
@property UInt32 id;
@property (strong) NSData* baseKey;
@property (strong) NSData* ratchetKey;
@property (strong) NSData* identityKey;
@property (strong) NSData* baseKeySignature;
@end

@implementation KeyExchangeMessage

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value_ {
  hasId_ = !!value_;
}
@synthesize id;
- (BOOL) hasBaseKey {
  return !!hasBaseKey_;
}
- (void) setHasBaseKey:(BOOL) value_ {
  hasBaseKey_ = !!value_;
}
@synthesize baseKey;
- (BOOL) hasRatchetKey {
  return !!hasRatchetKey_;
}
- (void) setHasRatchetKey:(BOOL) value_ {
  hasRatchetKey_ = !!value_;
}
@synthesize ratchetKey;
- (BOOL) hasIdentityKey {
  return !!hasIdentityKey_;
}
- (void) setHasIdentityKey:(BOOL) value_ {
  hasIdentityKey_ = !!value_;
}
@synthesize identityKey;
- (BOOL) hasBaseKeySignature {
  return !!hasBaseKeySignature_;
}
- (void) setHasBaseKeySignature:(BOOL) value_ {
  hasBaseKeySignature_ = !!value_;
}
@synthesize baseKeySignature;
- (id) init {
  if ((self = [super init])) {
    self.id = 0;
    self.baseKey = [NSData data];
    self.ratchetKey = [NSData data];
    self.identityKey = [NSData data];
    self.baseKeySignature = [NSData data];
  }
  return self;
}
static KeyExchangeMessage* defaultKeyExchangeMessageInstance = nil;
+ (void) initialize {
  if (self == [KeyExchangeMessage class]) {
    defaultKeyExchangeMessageInstance = [[KeyExchangeMessage alloc] init];
  }
}
+ (KeyExchangeMessage*) defaultInstance {
  return defaultKeyExchangeMessageInstance;
}
- (KeyExchangeMessage*) defaultInstance {
  return defaultKeyExchangeMessageInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeUInt32:1 value:self.id];
  }
  if (self.hasBaseKey) {
    [output writeData:2 value:self.baseKey];
  }
  if (self.hasRatchetKey) {
    [output writeData:3 value:self.ratchetKey];
  }
  if (self.hasIdentityKey) {
    [output writeData:4 value:self.identityKey];
  }
  if (self.hasBaseKeySignature) {
    [output writeData:5 value:self.baseKeySignature];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasId) {
    size_ += computeUInt32Size(1, self.id);
  }
  if (self.hasBaseKey) {
    size_ += computeDataSize(2, self.baseKey);
  }
  if (self.hasRatchetKey) {
    size_ += computeDataSize(3, self.ratchetKey);
  }
  if (self.hasIdentityKey) {
    size_ += computeDataSize(4, self.identityKey);
  }
  if (self.hasBaseKeySignature) {
    size_ += computeDataSize(5, self.baseKeySignature);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (KeyExchangeMessage*) parseFromData:(NSData*) data {
  return (KeyExchangeMessage*)[[[KeyExchangeMessage builder] mergeFromData:data] build];
}
+ (KeyExchangeMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (KeyExchangeMessage*)[[[KeyExchangeMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (KeyExchangeMessage*) parseFromInputStream:(NSInputStream*) input {
  return (KeyExchangeMessage*)[[[KeyExchangeMessage builder] mergeFromInputStream:input] build];
}
+ (KeyExchangeMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (KeyExchangeMessage*)[[[KeyExchangeMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (KeyExchangeMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (KeyExchangeMessage*)[[[KeyExchangeMessage builder] mergeFromCodedInputStream:input] build];
}
+ (KeyExchangeMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (KeyExchangeMessage*)[[[KeyExchangeMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (KeyExchangeMessageBuilder*) builder {
  return [[KeyExchangeMessageBuilder alloc] init];
}
+ (KeyExchangeMessageBuilder*) builderWithPrototype:(KeyExchangeMessage*) prototype {
  return [[KeyExchangeMessage builder] mergeFrom:prototype];
}
- (KeyExchangeMessageBuilder*) builder {
  return [KeyExchangeMessage builder];
}
- (KeyExchangeMessageBuilder*) toBuilder {
  return [KeyExchangeMessage builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"id", [NSNumber numberWithInteger:self.id]];
  }
  if (self.hasBaseKey) {
    [output appendFormat:@"%@%@: %@\n", indent, @"baseKey", self.baseKey];
  }
  if (self.hasRatchetKey) {
    [output appendFormat:@"%@%@: %@\n", indent, @"ratchetKey", self.ratchetKey];
  }
  if (self.hasIdentityKey) {
    [output appendFormat:@"%@%@: %@\n", indent, @"identityKey", self.identityKey];
  }
  if (self.hasBaseKeySignature) {
    [output appendFormat:@"%@%@: %@\n", indent, @"baseKeySignature", self.baseKeySignature];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[KeyExchangeMessage class]]) {
    return NO;
  }
  KeyExchangeMessage *otherMessage = other;
  return
      self.hasId == otherMessage.hasId &&
      (!self.hasId || self.id == otherMessage.id) &&
      self.hasBaseKey == otherMessage.hasBaseKey &&
      (!self.hasBaseKey || [self.baseKey isEqual:otherMessage.baseKey]) &&
      self.hasRatchetKey == otherMessage.hasRatchetKey &&
      (!self.hasRatchetKey || [self.ratchetKey isEqual:otherMessage.ratchetKey]) &&
      self.hasIdentityKey == otherMessage.hasIdentityKey &&
      (!self.hasIdentityKey || [self.identityKey isEqual:otherMessage.identityKey]) &&
      self.hasBaseKeySignature == otherMessage.hasBaseKeySignature &&
      (!self.hasBaseKeySignature || [self.baseKeySignature isEqual:otherMessage.baseKeySignature]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.id] hash];
  }
  if (self.hasBaseKey) {
    hashCode = hashCode * 31 + [self.baseKey hash];
  }
  if (self.hasRatchetKey) {
    hashCode = hashCode * 31 + [self.ratchetKey hash];
  }
  if (self.hasIdentityKey) {
    hashCode = hashCode * 31 + [self.identityKey hash];
  }
  if (self.hasBaseKeySignature) {
    hashCode = hashCode * 31 + [self.baseKeySignature hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface KeyExchangeMessageBuilder()
@property (strong) KeyExchangeMessage* result;
@end

@implementation KeyExchangeMessageBuilder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[KeyExchangeMessage alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (KeyExchangeMessageBuilder*) clear {
  self.result = [[KeyExchangeMessage alloc] init];
  return self;
}
- (KeyExchangeMessageBuilder*) clone {
  return [KeyExchangeMessage builderWithPrototype:result];
}
- (KeyExchangeMessage*) defaultInstance {
  return [KeyExchangeMessage defaultInstance];
}
- (KeyExchangeMessage*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (KeyExchangeMessage*) buildPartial {
  KeyExchangeMessage* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (KeyExchangeMessageBuilder*) mergeFrom:(KeyExchangeMessage*) other {
  if (other == [KeyExchangeMessage defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasBaseKey) {
    [self setBaseKey:other.baseKey];
  }
  if (other.hasRatchetKey) {
    [self setRatchetKey:other.ratchetKey];
  }
  if (other.hasIdentityKey) {
    [self setIdentityKey:other.identityKey];
  }
  if (other.hasBaseKeySignature) {
    [self setBaseKeySignature:other.baseKeySignature];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (KeyExchangeMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (KeyExchangeMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setId:[input readUInt32]];
        break;
      }
      case 18: {
        [self setBaseKey:[input readData]];
        break;
      }
      case 26: {
        [self setRatchetKey:[input readData]];
        break;
      }
      case 34: {
        [self setIdentityKey:[input readData]];
        break;
      }
      case 42: {
        [self setBaseKeySignature:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return result.hasId;
}
- (UInt32) id {
  return result.id;
}
- (KeyExchangeMessageBuilder*) setId:(UInt32) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (KeyExchangeMessageBuilder*) clearId {
  result.hasId = NO;
  result.id = 0;
  return self;
}
- (BOOL) hasBaseKey {
  return result.hasBaseKey;
}
- (NSData*) baseKey {
  return result.baseKey;
}
- (KeyExchangeMessageBuilder*) setBaseKey:(NSData*) value {
  result.hasBaseKey = YES;
  result.baseKey = value;
  return self;
}
- (KeyExchangeMessageBuilder*) clearBaseKey {
  result.hasBaseKey = NO;
  result.baseKey = [NSData data];
  return self;
}
- (BOOL) hasRatchetKey {
  return result.hasRatchetKey;
}
- (NSData*) ratchetKey {
  return result.ratchetKey;
}
- (KeyExchangeMessageBuilder*) setRatchetKey:(NSData*) value {
  result.hasRatchetKey = YES;
  result.ratchetKey = value;
  return self;
}
- (KeyExchangeMessageBuilder*) clearRatchetKey {
  result.hasRatchetKey = NO;
  result.ratchetKey = [NSData data];
  return self;
}
- (BOOL) hasIdentityKey {
  return result.hasIdentityKey;
}
- (NSData*) identityKey {
  return result.identityKey;
}
- (KeyExchangeMessageBuilder*) setIdentityKey:(NSData*) value {
  result.hasIdentityKey = YES;
  result.identityKey = value;
  return self;
}
- (KeyExchangeMessageBuilder*) clearIdentityKey {
  result.hasIdentityKey = NO;
  result.identityKey = [NSData data];
  return self;
}
- (BOOL) hasBaseKeySignature {
  return result.hasBaseKeySignature;
}
- (NSData*) baseKeySignature {
  return result.baseKeySignature;
}
- (KeyExchangeMessageBuilder*) setBaseKeySignature:(NSData*) value {
  result.hasBaseKeySignature = YES;
  result.baseKeySignature = value;
  return self;
}
- (KeyExchangeMessageBuilder*) clearBaseKeySignature {
  result.hasBaseKeySignature = NO;
  result.baseKeySignature = [NSData data];
  return self;
}
@end

@interface SenderKeyMessage ()
@property UInt32 id;
@property UInt32 iteration;
@property (strong) NSData* ciphertext;
@end

@implementation SenderKeyMessage

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value_ {
  hasId_ = !!value_;
}
@synthesize id;
- (BOOL) hasIteration {
  return !!hasIteration_;
}
- (void) setHasIteration:(BOOL) value_ {
  hasIteration_ = !!value_;
}
@synthesize iteration;
- (BOOL) hasCiphertext {
  return !!hasCiphertext_;
}
- (void) setHasCiphertext:(BOOL) value_ {
  hasCiphertext_ = !!value_;
}
@synthesize ciphertext;
- (id) init {
  if ((self = [super init])) {
    self.id = 0;
    self.iteration = 0;
    self.ciphertext = [NSData data];
  }
  return self;
}
static SenderKeyMessage* defaultSenderKeyMessageInstance = nil;
+ (void) initialize {
  if (self == [SenderKeyMessage class]) {
    defaultSenderKeyMessageInstance = [[SenderKeyMessage alloc] init];
  }
}
+ (SenderKeyMessage*) defaultInstance {
  return defaultSenderKeyMessageInstance;
}
- (SenderKeyMessage*) defaultInstance {
  return defaultSenderKeyMessageInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeUInt32:1 value:self.id];
  }
  if (self.hasIteration) {
    [output writeUInt32:2 value:self.iteration];
  }
  if (self.hasCiphertext) {
    [output writeData:3 value:self.ciphertext];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasId) {
    size_ += computeUInt32Size(1, self.id);
  }
  if (self.hasIteration) {
    size_ += computeUInt32Size(2, self.iteration);
  }
  if (self.hasCiphertext) {
    size_ += computeDataSize(3, self.ciphertext);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (SenderKeyMessage*) parseFromData:(NSData*) data {
  return (SenderKeyMessage*)[[[SenderKeyMessage builder] mergeFromData:data] build];
}
+ (SenderKeyMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SenderKeyMessage*)[[[SenderKeyMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (SenderKeyMessage*) parseFromInputStream:(NSInputStream*) input {
  return (SenderKeyMessage*)[[[SenderKeyMessage builder] mergeFromInputStream:input] build];
}
+ (SenderKeyMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SenderKeyMessage*)[[[SenderKeyMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SenderKeyMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (SenderKeyMessage*)[[[SenderKeyMessage builder] mergeFromCodedInputStream:input] build];
}
+ (SenderKeyMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SenderKeyMessage*)[[[SenderKeyMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SenderKeyMessageBuilder*) builder {
  return [[SenderKeyMessageBuilder alloc] init];
}
+ (SenderKeyMessageBuilder*) builderWithPrototype:(SenderKeyMessage*) prototype {
  return [[SenderKeyMessage builder] mergeFrom:prototype];
}
- (SenderKeyMessageBuilder*) builder {
  return [SenderKeyMessage builder];
}
- (SenderKeyMessageBuilder*) toBuilder {
  return [SenderKeyMessage builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"id", [NSNumber numberWithInteger:self.id]];
  }
  if (self.hasIteration) {
    [output appendFormat:@"%@%@: %@\n", indent, @"iteration", [NSNumber numberWithInteger:self.iteration]];
  }
  if (self.hasCiphertext) {
    [output appendFormat:@"%@%@: %@\n", indent, @"ciphertext", self.ciphertext];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[SenderKeyMessage class]]) {
    return NO;
  }
  SenderKeyMessage *otherMessage = other;
  return
      self.hasId == otherMessage.hasId &&
      (!self.hasId || self.id == otherMessage.id) &&
      self.hasIteration == otherMessage.hasIteration &&
      (!self.hasIteration || self.iteration == otherMessage.iteration) &&
      self.hasCiphertext == otherMessage.hasCiphertext &&
      (!self.hasCiphertext || [self.ciphertext isEqual:otherMessage.ciphertext]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.id] hash];
  }
  if (self.hasIteration) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.iteration] hash];
  }
  if (self.hasCiphertext) {
    hashCode = hashCode * 31 + [self.ciphertext hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface SenderKeyMessageBuilder()
@property (strong) SenderKeyMessage* result;
@end

@implementation SenderKeyMessageBuilder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[SenderKeyMessage alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (SenderKeyMessageBuilder*) clear {
  self.result = [[SenderKeyMessage alloc] init];
  return self;
}
- (SenderKeyMessageBuilder*) clone {
  return [SenderKeyMessage builderWithPrototype:result];
}
- (SenderKeyMessage*) defaultInstance {
  return [SenderKeyMessage defaultInstance];
}
- (SenderKeyMessage*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (SenderKeyMessage*) buildPartial {
  SenderKeyMessage* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (SenderKeyMessageBuilder*) mergeFrom:(SenderKeyMessage*) other {
  if (other == [SenderKeyMessage defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasIteration) {
    [self setIteration:other.iteration];
  }
  if (other.hasCiphertext) {
    [self setCiphertext:other.ciphertext];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (SenderKeyMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (SenderKeyMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setId:[input readUInt32]];
        break;
      }
      case 16: {
        [self setIteration:[input readUInt32]];
        break;
      }
      case 26: {
        [self setCiphertext:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return result.hasId;
}
- (UInt32) id {
  return result.id;
}
- (SenderKeyMessageBuilder*) setId:(UInt32) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (SenderKeyMessageBuilder*) clearId {
  result.hasId = NO;
  result.id = 0;
  return self;
}
- (BOOL) hasIteration {
  return result.hasIteration;
}
- (UInt32) iteration {
  return result.iteration;
}
- (SenderKeyMessageBuilder*) setIteration:(UInt32) value {
  result.hasIteration = YES;
  result.iteration = value;
  return self;
}
- (SenderKeyMessageBuilder*) clearIteration {
  result.hasIteration = NO;
  result.iteration = 0;
  return self;
}
- (BOOL) hasCiphertext {
  return result.hasCiphertext;
}
- (NSData*) ciphertext {
  return result.ciphertext;
}
- (SenderKeyMessageBuilder*) setCiphertext:(NSData*) value {
  result.hasCiphertext = YES;
  result.ciphertext = value;
  return self;
}
- (SenderKeyMessageBuilder*) clearCiphertext {
  result.hasCiphertext = NO;
  result.ciphertext = [NSData data];
  return self;
}
@end

@interface SenderKeyDistributionMessage ()
@property UInt32 id;
@property UInt32 iteration;
@property (strong) NSData* chainKey;
@property (strong) NSData* signingKey;
@end

@implementation SenderKeyDistributionMessage

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) value_ {
  hasId_ = !!value_;
}
@synthesize id;
- (BOOL) hasIteration {
  return !!hasIteration_;
}
- (void) setHasIteration:(BOOL) value_ {
  hasIteration_ = !!value_;
}
@synthesize iteration;
- (BOOL) hasChainKey {
  return !!hasChainKey_;
}
- (void) setHasChainKey:(BOOL) value_ {
  hasChainKey_ = !!value_;
}
@synthesize chainKey;
- (BOOL) hasSigningKey {
  return !!hasSigningKey_;
}
- (void) setHasSigningKey:(BOOL) value_ {
  hasSigningKey_ = !!value_;
}
@synthesize signingKey;
- (id) init {
  if ((self = [super init])) {
    self.id = 0;
    self.iteration = 0;
    self.chainKey = [NSData data];
    self.signingKey = [NSData data];
  }
  return self;
}
static SenderKeyDistributionMessage* defaultSenderKeyDistributionMessageInstance = nil;
+ (void) initialize {
  if (self == [SenderKeyDistributionMessage class]) {
    defaultSenderKeyDistributionMessageInstance = [[SenderKeyDistributionMessage alloc] init];
  }
}
+ (SenderKeyDistributionMessage*) defaultInstance {
  return defaultSenderKeyDistributionMessageInstance;
}
- (SenderKeyDistributionMessage*) defaultInstance {
  return defaultSenderKeyDistributionMessageInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeUInt32:1 value:self.id];
  }
  if (self.hasIteration) {
    [output writeUInt32:2 value:self.iteration];
  }
  if (self.hasChainKey) {
    [output writeData:3 value:self.chainKey];
  }
  if (self.hasSigningKey) {
    [output writeData:4 value:self.signingKey];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasId) {
    size_ += computeUInt32Size(1, self.id);
  }
  if (self.hasIteration) {
    size_ += computeUInt32Size(2, self.iteration);
  }
  if (self.hasChainKey) {
    size_ += computeDataSize(3, self.chainKey);
  }
  if (self.hasSigningKey) {
    size_ += computeDataSize(4, self.signingKey);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (SenderKeyDistributionMessage*) parseFromData:(NSData*) data {
  return (SenderKeyDistributionMessage*)[[[SenderKeyDistributionMessage builder] mergeFromData:data] build];
}
+ (SenderKeyDistributionMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SenderKeyDistributionMessage*)[[[SenderKeyDistributionMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (SenderKeyDistributionMessage*) parseFromInputStream:(NSInputStream*) input {
  return (SenderKeyDistributionMessage*)[[[SenderKeyDistributionMessage builder] mergeFromInputStream:input] build];
}
+ (SenderKeyDistributionMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SenderKeyDistributionMessage*)[[[SenderKeyDistributionMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SenderKeyDistributionMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (SenderKeyDistributionMessage*)[[[SenderKeyDistributionMessage builder] mergeFromCodedInputStream:input] build];
}
+ (SenderKeyDistributionMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SenderKeyDistributionMessage*)[[[SenderKeyDistributionMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SenderKeyDistributionMessageBuilder*) builder {
  return [[SenderKeyDistributionMessageBuilder alloc] init];
}
+ (SenderKeyDistributionMessageBuilder*) builderWithPrototype:(SenderKeyDistributionMessage*) prototype {
  return [[SenderKeyDistributionMessage builder] mergeFrom:prototype];
}
- (SenderKeyDistributionMessageBuilder*) builder {
  return [SenderKeyDistributionMessage builder];
}
- (SenderKeyDistributionMessageBuilder*) toBuilder {
  return [SenderKeyDistributionMessage builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"id", [NSNumber numberWithInteger:self.id]];
  }
  if (self.hasIteration) {
    [output appendFormat:@"%@%@: %@\n", indent, @"iteration", [NSNumber numberWithInteger:self.iteration]];
  }
  if (self.hasChainKey) {
    [output appendFormat:@"%@%@: %@\n", indent, @"chainKey", self.chainKey];
  }
  if (self.hasSigningKey) {
    [output appendFormat:@"%@%@: %@\n", indent, @"signingKey", self.signingKey];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[SenderKeyDistributionMessage class]]) {
    return NO;
  }
  SenderKeyDistributionMessage *otherMessage = other;
  return
      self.hasId == otherMessage.hasId &&
      (!self.hasId || self.id == otherMessage.id) &&
      self.hasIteration == otherMessage.hasIteration &&
      (!self.hasIteration || self.iteration == otherMessage.iteration) &&
      self.hasChainKey == otherMessage.hasChainKey &&
      (!self.hasChainKey || [self.chainKey isEqual:otherMessage.chainKey]) &&
      self.hasSigningKey == otherMessage.hasSigningKey &&
      (!self.hasSigningKey || [self.signingKey isEqual:otherMessage.signingKey]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.id] hash];
  }
  if (self.hasIteration) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.iteration] hash];
  }
  if (self.hasChainKey) {
    hashCode = hashCode * 31 + [self.chainKey hash];
  }
  if (self.hasSigningKey) {
    hashCode = hashCode * 31 + [self.signingKey hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface SenderKeyDistributionMessageBuilder()
@property (strong) SenderKeyDistributionMessage* result;
@end

@implementation SenderKeyDistributionMessageBuilder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[SenderKeyDistributionMessage alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (SenderKeyDistributionMessageBuilder*) clear {
  self.result = [[SenderKeyDistributionMessage alloc] init];
  return self;
}
- (SenderKeyDistributionMessageBuilder*) clone {
  return [SenderKeyDistributionMessage builderWithPrototype:result];
}
- (SenderKeyDistributionMessage*) defaultInstance {
  return [SenderKeyDistributionMessage defaultInstance];
}
- (SenderKeyDistributionMessage*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (SenderKeyDistributionMessage*) buildPartial {
  SenderKeyDistributionMessage* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (SenderKeyDistributionMessageBuilder*) mergeFrom:(SenderKeyDistributionMessage*) other {
  if (other == [SenderKeyDistributionMessage defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasIteration) {
    [self setIteration:other.iteration];
  }
  if (other.hasChainKey) {
    [self setChainKey:other.chainKey];
  }
  if (other.hasSigningKey) {
    [self setSigningKey:other.signingKey];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (SenderKeyDistributionMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (SenderKeyDistributionMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setId:[input readUInt32]];
        break;
      }
      case 16: {
        [self setIteration:[input readUInt32]];
        break;
      }
      case 26: {
        [self setChainKey:[input readData]];
        break;
      }
      case 34: {
        [self setSigningKey:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return result.hasId;
}
- (UInt32) id {
  return result.id;
}
- (SenderKeyDistributionMessageBuilder*) setId:(UInt32) value {
  result.hasId = YES;
  result.id = value;
  return self;
}
- (SenderKeyDistributionMessageBuilder*) clearId {
  result.hasId = NO;
  result.id = 0;
  return self;
}
- (BOOL) hasIteration {
  return result.hasIteration;
}
- (UInt32) iteration {
  return result.iteration;
}
- (SenderKeyDistributionMessageBuilder*) setIteration:(UInt32) value {
  result.hasIteration = YES;
  result.iteration = value;
  return self;
}
- (SenderKeyDistributionMessageBuilder*) clearIteration {
  result.hasIteration = NO;
  result.iteration = 0;
  return self;
}
- (BOOL) hasChainKey {
  return result.hasChainKey;
}
- (NSData*) chainKey {
  return result.chainKey;
}
- (SenderKeyDistributionMessageBuilder*) setChainKey:(NSData*) value {
  result.hasChainKey = YES;
  result.chainKey = value;
  return self;
}
- (SenderKeyDistributionMessageBuilder*) clearChainKey {
  result.hasChainKey = NO;
  result.chainKey = [NSData data];
  return self;
}
- (BOOL) hasSigningKey {
  return result.hasSigningKey;
}
- (NSData*) signingKey {
  return result.signingKey;
}
- (SenderKeyDistributionMessageBuilder*) setSigningKey:(NSData*) value {
  result.hasSigningKey = YES;
  result.signingKey = value;
  return self;
}
- (SenderKeyDistributionMessageBuilder*) clearSigningKey {
  result.hasSigningKey = NO;
  result.signingKey = [NSData data];
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
